source 'https://rubygems.org'

gem 'rails', '3.0.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'bundler'
gem 'uuidtools'
gem 'mysql2'
gem 'activerecord-mysql2-adapter'
